# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET-Lambda

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install Dotnet Lambda Global CLI
      run: dotnet tool install -g Amazon.Lambda.Tools && export PATH="$PATH:/home/ubuntu/.dotnet/tools"
    - name: Build Lambda function
      run: cd function/dotnet_lambda_app && dotnet lambda package ../app.zip
      
